### ISSUE TITLE
Join lines region for search query

### ISSUE THREAD

**Issue by akuroiwa** [keyword-search/keyword-search#4]
I wrote this code for the purpose of being close to `browse-apropos-url`:

``` lisp
(defun keyword-search-get-query ()
  "Return the selected region (if any) or the symbol at point.
This function was copied from `engine-mode.el'."
  (if (use-region-p)
      (replace-regexp-in-string
       "^\s-*\\|\s-*$" ""
       (replace-regexp-in-string
    "[\u3000\s\t\n]+" "\s"
    (buffer-substring (region-beginning) (region-end))))
    (thing-at-point 'symbol)))
```

It seems that `xah-replace-pairs` written by Mr. @xahlee is suitable to eliminate redundancy:

``` lisp
(require 'xah-replace-pairs)
(defun keyword-search-get-query ()
  "Return the selected region (if any) or the symbol at point.
This function was copied from `engine-mode.el'."
  (if (use-region-p)
      (xah-replace-regexp-pairs-in-string
       (buffer-substring (region-beginning) (region-end))
       '(
     ["[\u3000\s\t\n]+" "\s"]
     ["^\s-*\\|\s-*$" ""]
     ))
    (thing-at-point 'symbol)))
```

Does anyone have a good idea to join lines?

**Comment by xahlee** [comment]
In this in your case it's better just to use plain emacs than using my 'xah-replace-pairs, because it's just 2 replacements. Faster and simpler if you just use plain elisp.

What do you mean by join lines? You want to remove linebreaks? That can be done with regex of "\n+" to " ".

**Comment by akuroiwa** [comment]
Thank you for replying, Mr. @xahlee.
I will do as you wrote.

I want to add a feature such as a combination of `delete-indentation`, `just-one-space`, `delete-horizontal-space` and `delete-trailing-whitespace` based on [browse-apropos-url](http://www.emacswiki.org/emacs/BrowseAproposURL).

**Comment by xahlee** [comment]
I'm not sure what you mean by "based on browse-apropos-url".

You can remove tabs, remove extra spaces, and delete space before and after, on a region, or a string. One or 2 regex should do. I think using replace-regexp-in-string 1 or 2 times should do what you want. Your regex already does much of it. Were you asking about how??

**Comment by akuroiwa** [comment]
Thank you for your advice.
I pushed [new commit](https://github.com/keyword-search/keyword-search/commit/1a01e3d5a43e48701cfab0332876284f5d3a1bba) as you wrote.

`browse-apropos-url` is the original code of `keyword-search`.

I think your `xah-replace-pairs` can avoid waste and complicated work.
I would suggest that you add a new function for the above-mentioned feature on a region or a string in `xah-replace-pairs`.

It will be useful and frequently-used function for Emacs users.
Please consider that.
