### ISSUE TITLE
keyword-search without double confirmation?

### ISSUE THREAD

**Issue by svenha** [keyword-search/keyword-search#6]
Is it possible to search for the keyword under the cursor, but without the two questions about the search engine and the keyword?

**Comment by akuroiwa** [comment]
No, You can't do that.  You have to answer at least one question.
`keyword-search-at-point` or `keyword-search-quick-additionally` will help you to search for the symbol at point or the region.

* <kbd>C-h f keyword-search-at-point [RET]</kbd>
* <kbd>C-h v keyword-search-default [RET]</kbd>

**Comment by svenha** [comment]
Thanks @akuroiwa . At least, I can use 1 extra Enter instead of 2.

**Comment by akuroiwa** [comment]
Not at all.
If you come up with a solution, please feel free to submit a pull request.
